---
title: "JSC370 HW5(Pre-Final project) Visualizations"
author: "Shiyuan Zhou"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

<br>

I will showcase a few interactive visuals in this page

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(dplyr)
library(data.table)
library(tidyverse)
library(plotly)
library(knitr)
library(widgetframe)

data <- read.csv('Life Expectancy Data.csv', check.names = F)
for(i in 1:ncol(data)) {
  data[ , i][is.na(data[ , i])] <- mean(data[ , i], na.rm = TRUE)
}

data <- data[ which(data$ `Income composition of resources` > 0.0), ]
dt <- data.table(data)

dta <- dt[, expenditure_level := case_when(dt[, `Total expenditure`] < 3 ~ "low", 
                               dt[, `Total expenditure`] <= 5 ~ "medium",
                               dt[, `Total expenditure`] <= 9 ~ "high",
                               dt[, `Total expenditure`] > 9 ~ "very high")
      ]

dt1 <- dta[, hdi_level := case_when(dta[, `Income composition of resources`] < 0.55 ~ "low", 
                               dta[, `Income composition of resources`] <= 0.7 ~ "medium",
                               dta[, `Income composition of resources`] <= 0.8 ~ "high",
                               dta[, `Income composition of resources`] > 0.8 ~ "very high")]

dt1$expenditure_level <- factor(dt1$expenditure_level, levels = c("low", "medium", "high", "very high"))
dt1$hdi_level <- factor(dt1$hdi_level, levels = c("low", "medium", "high", "very high"))

sexp <- dt1 %>% group_by(expenditure_level) %>%
  summarise(
    min_exp = min(`Total expenditure`, na.rm = TRUE),
    max_exp = max(`Total expenditure`, na.rm = TRUE),
    count = n()
  ) %>% arrange(expenditure_level)

shdi <- dt1 %>% group_by(hdi_level) %>%
  summarise(
    min_exp = min(`Income composition of resources`, na.rm = TRUE),
    max_exp = max(`Income composition of resources`, na.rm = TRUE),
    count = n()
  ) %>% arrange(hdi_level)
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```



# Interactive Visualization


```{r include=FALSE, warning=FALSE}
p1_plot <- ggplot(dt1, aes(x = `Income composition of resources`, y = `Life expectancy`, color = `Status`)) +
  geom_point(size = 0.5) +
  geom_smooth(data = dt1, formula = y ~ s(x, bs="cr",k=5), method = "gam", col=2) +
  theme_light() +
  labs(title = "Life expectancy vs ICR", x = "Income composition of resources", y = "Life expectancy") + theme(legend.position = c(0.8, 0.2))
p1_plot <- ggplotly(p1_plot)

# max_year <- max(data$Year)
new_data_2013 <- data %>% filter(Year==2013)

p2_plot <- new_data_2013 %>%
  plot_ly(x = ~`Adult Mortality`, y=~`Life expectancy`, type = 'scatter',
          mode = "markers", color = ~Country, size = ~`Total expenditure`,
          sizes = c(5, 70), marker = list(sizemode = "diameter", opacity = 0.5),
          hover_info = "text",
          text = ~paste(paste0("Country:", Country, "<br>"),
                        paste0("Life Expectancy:", `Life expectancy`),
                        paste0("Adult Mortality:", `Adult Mortality`),
                        paste0("Infant-Death per 1k:", `infant deaths`),
                        paste0("Under-Five-Death per 1k:", `under-five deaths`),
                        sep = "<br>")) %>%
  
  layout(title = "Adult Mortality-Life expectancy",
         yaxis = list(title = "Life expectancy"),
         xaxis = list(title = "Adult Mortality"),
         hovermode = "compare")

p3_plot <- dt1 %>%
  plot_ly(x = ~`Income composition of resources`, y = ~`Life expectancy`, color = ~Country, type = "scatter", mode = "lines")
```

# {.tabset}

## First plot

Testing for sharing information about plot 1

```{r warning=FALSE, echo=FALSE}
p1_plot
```

## Second plot

```{r warning=FALSE, echo=FALSE}
p2_plot
```

## Third plot

```{r warning=FALSE, echo=FALSE}
p3_plot
```

# {-}


<br>
<br>